# Cloud Build pipeline: build -> push -> deploy to GKE
# Hard-coded configuration for new-project-23jan2025
#
# Built-in vars used: $PROJECT_ID, $SHORT_SHA
#
# Strategy:
#   - Build image with :$SHORT_SHA and :latest
#   - Push both tags
#   - Apply k8s manifests (image in manifest is 'latest')
#   - Force a rollout restart so pods pull the new 'latest'

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - id: "Docker build"
    name: "gcr.io/cloud-builders/docker"
    env:
      - "IMAGE=asia-south1-docker.pkg.dev/new-project-23jan2025/my-docker-repo/hello-app"
    args:
      [
        "build",
        "-t","$IMAGE:$SHORT_SHA",
        "-t","$IMAGE:latest",
        "."
      ]

  - id: "Push :$SHORT_SHA"
    name: "gcr.io/cloud-builders/docker"
    env:
      - "IMAGE=asia-south1-docker.pkg.dev/new-project-23jan2025/my-docker-repo/hello-app"
    args: ["push","$IMAGE:$SHORT_SHA"]

  - id: "Push :latest"
    name: "gcr.io/cloud-builders/docker"
    env:
      - "IMAGE=asia-south1-docker.pkg.dev/new-project-23jan2025/my-docker-repo/hello-app"
    args: ["push","$IMAGE:latest"]

  - id: "Get GKE credentials"
    name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "container","clusters","get-credentials","my-gke-cluster",  # Replace with your GKE cluster name
        "--region","asia-south1",                                   # Replace with your GKE region
        "--project","$PROJECT_ID"
      ]

  - id: "Create namespace (if missing)"
    name: "gcr.io/cloud-builders/kubectl"
    env:
      - "CLOUDSDK_COMPUTE_REGION=asia-south1"      # Replace with your GKE region
      - "CLOUDSDK_CONTAINER_CLUSTER=my-gke-cluster" # Replace with your GKE cluster name
    args:
      [
        "create","ns","default","--dry-run=client","-o","yaml"
      ]
    entrypoint: "bash"
    script: |
      set -euo pipefail
      kubectl create ns "default" --dry-run=client -o yaml | kubectl apply -f -

  - id: "Apply manifests"
    name: "gcr.io/cloud-builders/kubectl"
    args: ["apply","-f","k8s/","-n","default"]

  - id: "Rollout restart (pull new image)"
    name: "gcr.io/cloud-builders/kubectl"
    args: ["rollout","restart","deployment/hello-app","-n","default"]

  - id: "Wait for rollout"
    name: "gcr.io/cloud-builders/kubectl"
    args: ["rollout","status","deployment/hello-app","-n","default","--timeout=180s"]

images:
  - "asia-south1-docker.pkg.dev/new-project-23jan2025/my-docker-repo/hello-app:$SHORT_SHA"
  - "asia-south1-docker.pkg.dev/new-project-23jan2025/my-docker-repo/hello-app:latest"
